version: '3.9'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: webtronics_db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  app:
    restart: always
    build:
      context: .
      dockerfile: web.Dockerfile
      target: builder-base
    volumes:
      - ./app:/app
    container_name: webtronics_app
    env_file: .env
    ports:
      - ${SERVER_PORT-8000}:8000
    entrypoint: ["/code/entrypoint.sh"]
    depends_on:
      - db

volumes:
  postgres_data:
