version: '3.9'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: dayana-db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  app:
    restart: always
    build:
      context: .
      dockerfile: web.Dockerfile
      target: builder-base
    volumes:
      - ./app:/app
    container_name: 'app'
    env_file: .env
    ports:
      - ${SERVER_PORT-8000}:8000
    command: bash -c "uvicorn src.main:app --reload --workers 4 --host 0.0.0.0 --port 8000"
    depends_on:
      - db

volumes:
  postgres_data:
