"""create dislike tables

Revision ID: b14cb9e4421d
Revises: 9a691bd2bee7
Create Date: 2023-08-05 15:04:00.935328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b14cb9e4421d"
down_revision = "9a691bd2bee7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_dislike",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.alter_column("post_like", "post_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("post_like", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("post_like", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("post_like", "post_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_table("post_dislike")
    # ### end Alembic commands ###
