"""add ondelete to likes and dislikes tables

Revision ID: e05af2e8ff09
Revises: b14cb9e4421d
Create Date: 2023-08-05 17:44:31.226749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e05af2e8ff09"
down_revision = "b14cb9e4421d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("post_dislike_post_id_fkey", "post_dislike", type_="foreignkey")
    op.drop_constraint("post_dislike_user_id_fkey", "post_dislike", type_="foreignkey")
    op.create_foreign_key(
        None, "post_dislike", "post", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "post_dislike", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("post_like_user_id_fkey", "post_like", type_="foreignkey")
    op.drop_constraint("post_like_post_id_fkey", "post_like", type_="foreignkey")
    op.create_foreign_key(
        None, "post_like", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "post_like", "post", ["post_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post_like", type_="foreignkey")
    op.drop_constraint(None, "post_like", type_="foreignkey")
    op.create_foreign_key(
        "post_like_post_id_fkey", "post_like", "post", ["post_id"], ["id"]
    )
    op.create_foreign_key(
        "post_like_user_id_fkey", "post_like", "user", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "post_dislike", type_="foreignkey")
    op.drop_constraint(None, "post_dislike", type_="foreignkey")
    op.create_foreign_key(
        "post_dislike_user_id_fkey", "post_dislike", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "post_dislike_post_id_fkey", "post_dislike", "post", ["post_id"], ["id"]
    )
    # ### end Alembic commands ###
